// Code generated by Kitex v0.5.2. DO NOT EDIT.
package imservice

import (
	server "github.com/cloudwego/kitex/server"
	rpc "github.com/teekaytai/tiktok_server_assignment_2023/http-server/kitex_gen/rpc"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler rpc.IMService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
